@echo off
REM Terraform Import Script generated by gcloud cli

terraform import module.gcp.google_compute_backend_service.k8s_be_30600__0126f0d3e2a96ffe projects/k8slab-316013/global/backendServices/k8s-be-30600--0126f0d3e2a96ffe
terraform import module.gcp.google_compute_firewall.gke_k8s_cluster_484096b4_all projects/k8slab-316013/global/firewalls/gke-k8s-cluster-484096b4-all
terraform import module.gcp.google_compute_firewall.gke_k8s_cluster_484096b4_ssh projects/k8slab-316013/global/firewalls/gke-k8s-cluster-484096b4-ssh
terraform import module.gcp.google_compute_firewall.gke_k8s_cluster_484096b4_vms projects/k8slab-316013/global/firewalls/gke-k8s-cluster-484096b4-vms
terraform import module.gcp.google_compute_firewall.k8s_fw_l7__0126f0d3e2a96ffe projects/k8slab-316013/global/firewalls/k8s-fw-l7--0126f0d3e2a96ffe
terraform import module.gcp.google_compute_health_check.k8s_be_30600__0126f0d3e2a96ffe projects/k8slab-316013/global/healthChecks/k8s-be-30600--0126f0d3e2a96ffe
terraform import module.gcp.google_compute_instance_group.k8s_ig__0126f0d3e2a96ffe projects/k8slab-316013/zones/asia-southeast1-a/instanceGroups/k8s-ig--0126f0d3e2a96ffe
terraform import module.gcp.google_compute_instance_group.k8s_ig__0126f0d3e2a96ffe projects/k8slab-316013/zones/asia-southeast1-b/instanceGroups/k8s-ig--0126f0d3e2a96ffe
terraform import module.gcp.google_compute_instance_group.k8s_ig__131c205f75dbb014 projects/k8slab-316013/zones/us-central1-a/instanceGroups/k8s-ig--131c205f75dbb014
terraform import module.gcp.google_compute_instance_group.k8s_ig__73bf92b7164d6e85 projects/k8slab-316013/zones/us-east1-b/instanceGroups/k8s-ig--73bf92b7164d6e85
terraform import module.gcp.google_container_cluster.k8s_cluster k8slab-316013/asia-southeast1-a/k8s-cluster
terraform import module.gcp.google_service_account.639723339134_compute projects/k8slab-316013/serviceAccounts/639723339134-compute@k8slab-316013.iam.gserviceaccount.com
terraform import module.gcp.google_service_account.k8slab_316013 projects/k8slab-316013/serviceAccounts/k8slab-316013@k8slab-316013.iam.gserviceaccount.com
terraform import module.gcp.google_service_account.project_pod projects/k8slab-316013/serviceAccounts/project-pod@k8slab-316013.iam.gserviceaccount.com
